# This is the Bukkit configuration file in Paper.
# As you can see, there's actually not that much to configure without any plugins.
#
# If you need help with the configuration or have any questions related to Paper,
# join us in our Discord or check the docs page.
#
# File Reference: https://docs.papermc.io/paper/reference/bukkit-configuration/
# Docs: https://docs.papermc.io/
# Discord: https://discord.gg/papermc
# Website: https://papermc.io/

settings:
  allow-end: false
  warn-on-overload: true
  permissions-file: permissions.yml
  update-folder: update
  plugin-profiling: false
  connection-throttle: 4000
  query-plugins: true
  deprecated-verbose: default
  shutdown-message: Server closed
  minimum-api: none
  use-map-color-cache: true
spawn-limits:
  monsters: 0
  animals: 0
  water-animals: 0
  water-ambient: 0
  water-underground-creature: 0
  axolotls: 0
  ambient: 0
chunk-gc:
  period-in-ticks: 600
ticks-per:
  animal-spawns: 0
  monster-spawns: 0
  water-spawns: 0
  water-ambient-spawns: 0
  water-underground-creature-spawns: 0
  axolotl-spawns: 0
  ambient-spawns: 0
  autosave: 6000
aliases: now-in-commands.yml
