services:
  auto_review:
    container_name: auto_review_revenge_app
    build: .
    ports:
      - "37160:8080"
    restart: always

  redis:
    image: redis:7
    container_name: auto_review_revenge_redis